name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ["sargassum-world", "soe-sargassum-planktoscope"]
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: .

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Test gcloud CLI
        run: gcloud info

      - name: Download Packer Plugins
        run: packer init .

      - name: Build Image
        run: packer build -color=false -on-error=abort -var-file=${{ matrix.environment }}.pkrvars.hcl .
        env:
          PACKER_LOG: 1
          PKR_VAR_hashistack_nomad_bootstrap_token: ${{ secrets.NOMAD_BOOTSTRAP_TOKEN }}
