name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: .

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Download Packer Plugins
        uses: hashicorp/packer-github-actions@master
        with:
          command: init

      - name: Build Image
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort -var-file=sargassum-world.pkrvars.hcl"
          target: .
        env:
          PACKER_LOG: 1
          PKR_VAR_hashistack_nomad_bootstrap_token: ${{ secrets.NOMAD_BOOTSTRAP_TOKEN }}
