name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
#   HCP_ORGANIZATION_ID: ${{ secrets.HCP_ORGANIZATION_ID }}
#   HCP_PROJECT_ID: ${{ secrets.HCP_PROJECT_ID }}
#   HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
#   HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      iteration_id: ${{ steps.hcp.outputs.iteration_id }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Packer init
        run: packer init .

      - name: Packer Build
        run: packer build .

      # - name: Get HCP Packer Iteration ID from Packer Manifest
      #   id: hcp
      #   run: |
      #     last_run_uuid=$(jq -r '.last_run_uuid' "./packer_manifest.json")
      #     build=$(jq -r '.builds[] | select(.packer_run_uuid == "'"$last_run_uuid"'")' "./packer_manifest.json")
      #     iteration_id=$(echo "$build" | jq -r '.custom_data.iteration_id')
      #     echo "::set-output name=iteration_id::$iteration_id"
